FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json start.sh ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Generate Prisma Client
RUN npm run db:generate

# Can you filter the build down to just one app?
RUN npm run build:user-app
RUN npm run build:bank-webhook

# Make sure start.sh is executable
RUN chmod +x start.sh

CMD ["sh", "./start.sh"]