name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: tushardahiya/paytm_main:latest # Replace with your Docker Hub username and repository

      - name: Verify Pushed Image
        run: docker pull tushardahiya/paytm_main:latest # Replace with your Docker Hub username and repository

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }},JWT_SECRET=${{ secrets.JWT_SECRET }}
          script: |
            sudo docker pull tushardahiya/paytm_main:latest
            sudo docker stop paytm_main || true
            sudo docker rm paytm_main || true
            sudo docker run -d \
            -e NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e DATABASE_URL="${{ secrets.DATABASE_URL}}" \
            --name paytm_main -p 3000:3000 -p 3003:3003 tushardahiya/paytm_main:latest
